# Generated by Django 5.2.16 on 2026-08-03 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="加密密码")),
                (
                    "role",
                    models.CharField(
                        default="超级管理员", max_length=20, verbose_name="角色"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "管理员表",
                "db_table": "admin_user",
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "node_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="节点编码",
                    ),
                ),
                (
                    "node_name",
                    models.CharField(max_length=100, verbose_name="节点名称"),
                ),
                ("x", models.FloatField(verbose_name="地图X坐标")),
                ("y", models.FloatField(verbose_name="地图Y坐标")),
                ("node_type", models.CharField(max_length=30, verbose_name="节点类型")),
                ("people", models.IntegerField(default=0, verbose_name="实时人数")),
                ("density", models.FloatField(default=0.0, verbose_name="实时密度")),
                (
                    "level",
                    models.CharField(
                        default="low", max_length=20, verbose_name="拥挤等级"
                    ),
                ),
            ],
            options={
                "verbose_name": "交通网络节点表",
                "db_table": "network_node",
            },
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "alert_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="预警ID"
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(max_length=50, verbose_name="预警类型"),
                ),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="地点/节点"),
                ),
                ("details", models.TextField(verbose_name="详细说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发生时间"),
                ),
            ],
            options={
                "verbose_name": "安全预警日志表",
                "db_table": "security_alert",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "car_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="车辆ID",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="车主姓名"
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(max_length=20, verbose_name="车牌号"),
                ),
                (
                    "is_allowed",
                    models.BooleanField(default=True, verbose_name="是否允许准入"),
                ),
                (
                    "status",
                    models.CharField(
                        default="in_park", max_length=20, verbose_name="状态"
                    ),
                ),
            ],
            options={
                "verbose_name": "车辆管理表",
                "db_table": "vehicle",
            },
        ),
        migrations.CreateModel(
            name="Gate",
            fields=[
                (
                    "gate_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="门闸编号",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        default="open", max_length=20, verbose_name="控制模式"
                    ),
                ),
                (
                    "throughput_cap",
                    models.IntegerField(default=90, verbose_name="单位tick放行上限"),
                ),
                ("n_lanes", models.IntegerField(default=1, verbose_name="开闸数")),
                ("gate_status", models.IntegerField(default=1, verbose_name="状态码")),
                (
                    "gate_flow_rate",
                    models.FloatField(default=0.0, verbose_name="当前通行速率"),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gates",
                        to="core.node",
                        verbose_name="所属入口节点",
                    ),
                ),
            ],
            options={
                "verbose_name": "门闸设备表",
                "db_table": "gate_device",
            },
        ),
        migrations.CreateModel(
            name="SignalLight",
            fields=[
                (
                    "signal_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="红绿灯编号",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        default="adaptive", max_length=20, verbose_name="控制模式"
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        default="green", max_length=20, verbose_name="当前相位"
                    ),
                ),
                (
                    "cycle_time",
                    models.IntegerField(default=60, verbose_name="信号周期时长(秒)"),
                ),
                (
                    "green_time",
                    models.IntegerField(default=30, verbose_name="绿灯时长(秒)"),
                ),
                (
                    "yellow_time",
                    models.IntegerField(default=3, verbose_name="黄灯时长(秒)"),
                ),
                (
                    "red_time",
                    models.IntegerField(default=27, verbose_name="红灯时长(秒)"),
                ),
                (
                    "offset",
                    models.IntegerField(default=0, verbose_name="相位起始偏移(秒)"),
                ),
                (
                    "throughput_cap",
                    models.IntegerField(default=90, verbose_name="单位tick放行上限"),
                ),
                ("n_phases", models.IntegerField(default=2, verbose_name="相位数")),
                (
                    "signal_status",
                    models.IntegerField(default=1, verbose_name="状态码"),
                ),
                (
                    "signal_flow_rate",
                    models.FloatField(default=0.0, verbose_name="当前通行速率"),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signals",
                        to="core.node",
                        verbose_name="所属路口节点",
                    ),
                ),
            ],
            options={
                "verbose_name": "红绿灯设备表",
                "db_table": "signal_device",
            },
        ),
    ]
