# Generated by Django 5.2.16 on 2026-08-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="gate_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="门闸编号"
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="signal_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="红绿灯编号"
            ),
        ),
    ]
