# Generated by Django 5.2.16 on 2026-08-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_node_gate_id_node_signal_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="edge_ids",
            field=models.JSONField(
                blank=True, default=list, verbose_name="关联边编号列表"
            ),
        ),
    ]
