# Generated by Django 5.2.16 on 2026-08-03 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_node_edge_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="预警编号"
                    ),
                ),
                (
                    "node_name",
                    models.CharField(max_length=100, verbose_name="节点名称"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("yellow", "黄色预警"), ("red", "红色预警")],
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待处理"), ("resolved", "已解决")],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "trigger_source",
                    models.CharField(
                        choices=[
                            ("ai_prediction", "AI预测"),
                            ("macro_analysis", "宏观分析"),
                            ("gate_abnormal", "门闸异常"),
                        ],
                        default="ai_prediction",
                        max_length=50,
                        verbose_name="触发来源",
                    ),
                ),
                ("description", models.TextField(verbose_name="预警描述")),
                ("created_at", models.DateTimeField(verbose_name="创建时间")),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
                (
                    "action_taken",
                    models.TextField(blank=True, null=True, verbose_name="处置措施"),
                ),
                (
                    "event_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="D事件ID"
                    ),
                ),
                (
                    "current_density",
                    models.FloatField(blank=True, null=True, verbose_name="当前密度"),
                ),
                (
                    "threshold_density",
                    models.FloatField(blank=True, null=True, verbose_name="阈值密度"),
                ),
                (
                    "predicted_duration_min",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="预测持续时间"
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.node",
                        verbose_name="关联节点",
                    ),
                ),
            ],
            options={
                "verbose_name": "预警记录",
                "verbose_name_plural": "预警记录",
                "db_table": "alert",
            },
        ),
        migrations.DeleteModel(
            name="SecurityAlert",
        ),
    ]
